# Generated by Django 4.2.13 on 2024-05-16 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a comic title', max_length=200)),
                ('vertical_cover', models.ImageField(upload_to='comic-covers/vertical/', verbose_name='comic vertical cover')),
                ('horizontal_cover', models.ImageField(upload_to='comic-covers/horizontal/', verbose_name='comic horizontal cover')),
                ('read_count', models.IntegerField(verbose_name='read count')),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComicAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(help_text='Enter the (pen) name of the author', max_length=200, verbose_name='pen name')),
            ],
        ),
        migrations.CreateModel(
            name='ComicChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='chapter-covers/', verbose_name='chapter cover')),
                ('title', models.CharField(max_length=200, verbose_name='chapter title')),
                ('chapter_number', models.IntegerField(verbose_name='chapter number')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='published date')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.comic', verbose_name='comic')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='language name')),
                ('code', models.CharField(max_length=10, verbose_name='language code')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='profile name')),
                ('avatar', models.ImageField(help_text='Upload profile avatar', upload_to='profile-avatars/', verbose_name='profile avatar')),
                ('bio', models.TextField(max_length=500, verbose_name='profile bio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComicTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_title', models.CharField(help_text='Enter a translated title for the comic', max_length=200, verbose_name='translated title')),
                ('translated_summary', models.TextField(help_text='Enter a translated summary for the comic', max_length=1000, verbose_name='translated summary')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.comic', verbose_name='comic')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.language')),
            ],
        ),
        migrations.CreateModel(
            name='ComicChapterTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_title', models.CharField(max_length=200, verbose_name='translated title')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.comicchapter', verbose_name='comic chapter')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.language', verbose_name='chapter language')),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='author',
            field=models.ManyToManyField(to='trang_tranh.comicauthor', verbose_name='comic author'),
        ),
        migrations.AddField(
            model_name='comic',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.userprofile'),
        ),
        migrations.CreateModel(
            name='ChapterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_image', models.ImageField(upload_to='page-images/', verbose_name='page image')),
                ('page_number', models.IntegerField(verbose_name='page number')),
                ('comic_chapter_translation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.comicchaptertranslation')),
            ],
        ),
    ]
