# Generated by Django 4.2.13 on 2024-05-24 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(help_text='Enter the (pen) name of the author', max_length=200, verbose_name='pen name')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='chapter-covers/', verbose_name='cover')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('number', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='number')),
                ('counter', models.PositiveSmallIntegerField(default=1, verbose_name='counter')),
                ('extra', models.BooleanField(default=False, verbose_name='is extra chapter?')),
                ('read_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='read count')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='published date')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='translated title')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='published date')),
                ('read_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='read count')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.chapter', verbose_name='chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('vertical_cover', models.ImageField(upload_to='comic-covers/vertical/', verbose_name='vertical cover')),
                ('horizontal_cover', models.ImageField(blank=True, null=True, upload_to='comic-covers/horizontal/', verbose_name='horizontal cover')),
                ('square_cover', models.ImageField(blank=True, null=True, upload_to='comic-covers/square/', verbose_name='square cover')),
                ('read_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='read count')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='published date')),
                ('summary', models.TextField(blank=True, max_length=1000, null=True, verbose_name='summary')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('ja', 'Japanese')], default='en', max_length=10, verbose_name='default language')),
                ('schedule', models.CharField(choices=[('w', 'Weekly'), ('m', 'Monthly'), ('i', 'Indefinite')], default='w', help_text='Serializing schedule', max_length=1, verbose_name='schedule')),
                ('status', models.CharField(choices=[('o', 'Ongoing'), ('c', 'Complete'), ('h', 'Hiatus')], default='o', help_text='Serializing status', max_length=1, verbose_name='status')),
                ('author', models.ManyToManyField(to='trang_tranh.author', verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='profile name')),
                ('avatar', models.ImageField(blank=True, help_text='Upload profile avatar', null=True, upload_to='profile-avatars/', verbose_name='profile avatar')),
                ('bio', models.TextField(max_length=500, verbose_name='profile bio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page-image-translations/', verbose_name='page image')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='page number')),
                ('chapter_translation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.chaptertranslation', verbose_name='chapter translation')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page-images/', verbose_name='image')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='number')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.chapter', verbose_name='chapter')),
            ],
        ),
        migrations.CreateModel(
            name='ComicTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('ja', 'Japanese')], default='en', max_length=10, verbose_name='translation language')),
                ('title', models.CharField(help_text='Enter a translated title for the comic', max_length=200, verbose_name='translated title')),
                ('summary', models.TextField(help_text='Enter a translated summary for the comic', max_length=1000, verbose_name='translated summary')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.comic', verbose_name='comic')),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.userprofile', verbose_name='publisher'),
        ),
        migrations.AddField(
            model_name='chaptertranslation',
            name='comic_translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.comictranslation', verbose_name='comic translation'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.comic', verbose_name='comic'),
        ),
        migrations.AddConstraint(
            model_name='pagetranslation',
            constraint=models.UniqueConstraint(fields=('chapter_translation', 'number'), name='unique_page_translation_number'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('chapter', 'number'), name='unique_page_number'),
        ),
        migrations.AddConstraint(
            model_name='comictranslation',
            constraint=models.UniqueConstraint(fields=('comic', 'language'), name='unique_comic_translation_language'),
        ),
        migrations.AddConstraint(
            model_name='chaptertranslation',
            constraint=models.UniqueConstraint(fields=('chapter', 'comic_translation'), name='unique_chapter_per_comic_translation'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('comic', 'number'), name='unique_chapter_number'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('comic', 'counter'), name='unique_chapter_counter'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('comic', 'counter', 'number'), name='unique_chapter_counter_and_chapter_number'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('number__isnull', True), ('extra__exact', True)), models.Q(('number__isnull', False), ('extra__exact', False)), _connector='OR'), name='chapter_number_is_null_when_extra_chapter_is_true'),
        ),
    ]
