# Generated by Django 4.2.13 on 2024-05-19 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a comic title', max_length=200)),
                ('vertical_cover', models.ImageField(upload_to='comic-covers/vertical/', verbose_name='vertical cover')),
                ('horizontal_cover', models.ImageField(upload_to='comic-covers/horizontal/', verbose_name='horizontal cover')),
                ('square_cover', models.ImageField(blank=True, null=True, upload_to='comic-covers/square/', verbose_name='square cover')),
                ('read_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='read count')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='published date')),
                ('summary', models.TextField(blank=True, max_length=1000, null=True, verbose_name='comic summary')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], default='en', max_length=10, verbose_name='default language')),
                ('schedule', models.CharField(choices=[('w', 'Weekly'), ('m', 'Monthly'), ('i', 'Indefinite')], default='w', help_text='Serializing schedule', max_length=1, verbose_name='serializing schedule')),
                ('status', models.CharField(choices=[('o', 'Ongoing'), ('c', 'Complete'), ('h', 'Hiatus')], default='o', help_text='Serializing status', max_length=1, verbose_name='series status')),
            ],
        ),
        migrations.CreateModel(
            name='ComicAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(help_text='Enter the (pen) name of the author', max_length=200, verbose_name='pen name')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='profile name')),
                ('avatar', models.ImageField(blank=True, help_text='Upload profile avatar', null=True, upload_to='profile-avatars/', verbose_name='profile avatar')),
                ('bio', models.TextField(max_length=500, verbose_name='profile bio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComicTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], default='en', max_length=10, verbose_name='comic translation language')),
                ('translated_title', models.CharField(help_text='Enter a translated title for the comic', max_length=200, verbose_name='translated title')),
                ('translated_summary', models.TextField(help_text='Enter a translated summary for the comic', max_length=1000, verbose_name='translated summary')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.comic', verbose_name='comic')),
            ],
        ),
        migrations.CreateModel(
            name='ComicChapterTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='chapter number')),
                ('translated_title', models.CharField(max_length=200, verbose_name='translated title')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='published date')),
                ('chapter_counter', models.PositiveSmallIntegerField(default=1, verbose_name='chapter counter')),
                ('read_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='read count')),
                ('extra_chapter', models.BooleanField(default=False, verbose_name='extra chapter')),
                ('comic_translation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.comictranslation', verbose_name='comic translation')),
            ],
        ),
        migrations.CreateModel(
            name='ComicChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='chapter-covers/', verbose_name='chapter cover')),
                ('title', models.CharField(max_length=200, verbose_name='chapter title')),
                ('chapter_number', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='chapter number')),
                ('chapter_counter', models.PositiveSmallIntegerField(default=1, verbose_name='chapter counter')),
                ('extra_chapter', models.BooleanField(default=False, verbose_name='extra chapter')),
                ('read_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='read count')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='published date')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.comic', verbose_name='comic')),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='author',
            field=models.ManyToManyField(to='trang_tranh.comicauthor', verbose_name='comic author'),
        ),
        migrations.AddField(
            model_name='comic',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.userprofile', verbose_name='publisher'),
        ),
        migrations.CreateModel(
            name='ChapterPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_image', models.ImageField(upload_to='page-image-translations/', verbose_name='page image')),
                ('page_number', models.PositiveSmallIntegerField(default=1, verbose_name='page number')),
                ('chapter_translation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.comicchaptertranslation', verbose_name='chapter translation')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_image', models.ImageField(upload_to='page-images/', verbose_name='page image')),
                ('page_number', models.PositiveSmallIntegerField(default=1, verbose_name='page number')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.comicchapter', verbose_name='comic chapter')),
            ],
        ),
        migrations.AddConstraint(
            model_name='comicchaptertranslation',
            constraint=models.UniqueConstraint(fields=('comic_translation', 'chapter_number'), name='unique_comic_translation_chapter_number'),
        ),
        migrations.AddConstraint(
            model_name='comicchaptertranslation',
            constraint=models.UniqueConstraint(fields=('comic_translation', 'chapter_counter'), name='unique_comic_translation_chapter_counter'),
        ),
        migrations.AddConstraint(
            model_name='comicchaptertranslation',
            constraint=models.UniqueConstraint(fields=('comic_translation', 'chapter_counter', 'chapter_number'), name='comic_translation_chapter_counter_and_chapter_number'),
        ),
        migrations.AddConstraint(
            model_name='comicchapter',
            constraint=models.UniqueConstraint(fields=('comic', 'chapter_number'), name='unique_comic_chapter_number'),
        ),
        migrations.AddConstraint(
            model_name='comicchapter',
            constraint=models.UniqueConstraint(fields=('comic', 'chapter_counter'), name='unique_comic_chapter_counter'),
        ),
        migrations.AddConstraint(
            model_name='comicchapter',
            constraint=models.UniqueConstraint(fields=('comic', 'chapter_counter', 'chapter_number'), name='unique_comic_chapter_counter_and_chapter_number'),
        ),
        migrations.AddConstraint(
            model_name='comicchapter',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('chapter_number__isnull', True), ('extra_chapter__exact', True)), models.Q(('chapter_number__isnull', False), ('extra_chapter__exact', False)), _connector='OR'), name='comic_chapter_number_is_null_when_extra_chapter_is_true'),
        ),
        migrations.AddConstraint(
            model_name='chapterpagetranslation',
            constraint=models.UniqueConstraint(fields=('chapter_translation', 'page_number'), name='unique_chapter_translation_page_number'),
        ),
        migrations.AddConstraint(
            model_name='chapterpage',
            constraint=models.UniqueConstraint(fields=('chapter', 'page_number'), name='unique_chapter_page_number'),
        ),
    ]
