# Generated by Django 4.2.13 on 2024-05-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0002_author_chapter_chaptertranslation_comic_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('ja', 'Japanese')], default='en', max_length=10, verbose_name='default language'),
        ),
        migrations.CreateModel(
            name='AuthorTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('ja', 'Japanese')], default='en', max_length=10, verbose_name='translation language')),
                ('pen_name', models.CharField(max_length=200, verbose_name='pen name')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.author', verbose_name='author')),
            ],
        ),
    ]
