# Generated by Django 4.2.13 on 2024-05-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0002_comic_comicauthor_comicchapter_language_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='schedule',
            field=models.CharField(choices=[('w', 'Weekly'), ('m', 'Monthly'), ('i', 'Indefinite')], default='w', help_text='Serializing schedule', max_length=1, verbose_name='serializing schedule'),
        ),
        migrations.AddField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('o', 'Ongoing'), ('c', 'Complete'), ('h', 'Hiatus')], default='o', help_text='Serializing status', max_length=1, verbose_name='series status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='trang_tranh.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trang_tranh.userprofile'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='read count'),
        ),
    ]
