# Generated by Django 4.2.13 on 2024-05-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0002_comic_comicauthor_userprofile_comictranslation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comictranslation',
            constraint=models.UniqueConstraint(fields=('comic', 'language'), name='unique_comic_translation_language'),
        ),
    ]
