# Generated by Django 4.2.13 on 2024-05-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0003_comic_schedule_comic_status_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload profile avatar', null=True, upload_to='profile-avatars/', verbose_name='profile avatar'),
        ),
    ]
