# Generated by Django 4.2.13 on 2024-05-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0003_comictranslation_unique_comic_translation_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comictranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], default='en', max_length=10, verbose_name='translation language'),
        ),
    ]
