# Generated by Django 4.2.13 on 2024-05-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0003_author_default_language_authortranslation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='authortranslation',
            constraint=models.UniqueConstraint(fields=('author', 'language'), name='unique_author_language'),
        ),
    ]
