# Generated by Django 4.2.13 on 2024-05-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0004_alter_comictranslation_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicchaptertranslation',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='chapter-translation-covers/', verbose_name='chapter cover'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('ja', 'Japanese')], default='en', max_length=10, verbose_name='default language'),
        ),
        migrations.AlterField(
            model_name='comictranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('ja', 'Japanese')], default='en', max_length=10, verbose_name='translation language'),
        ),
    ]
