# Generated by Django 4.2.13 on 2024-06-02 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0004_authortranslation_unique_author_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('ja', 'Japanese')], max_length=10, verbose_name='name')),
                ('writing_mode', models.CharField(choices=[('h-tb', 'horizontal-tb'), ('v-rl', 'vertical-rl'), ('v-lr', 'vertical-lr')], max_length=10, verbose_name='writing mode')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(max_length=1000, verbose_name='text content')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('like', models.IntegerField(default=0, editable=False, verbose_name='like count')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trang_tranh.language', verbose_name='language')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trang_tranh.post', verbose_name='reply to')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trang_tranh.userprofile', verbose_name='user profile')),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post-images', verbose_name='image')),
                ('alt_text', models.TextField(max_length=1000, verbose_name='alternative text')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trang_tranh.post', verbose_name='post media')),
            ],
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_language'),
        ),
    ]
