# Generated by Django 4.2.13 on 2024-05-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='comic summary'),
        ),
    ]
