# Generated by Django 4.2.13 on 2024-06-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0005_language_post_postmedia_language_unique_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.AddField(
            model_name='post',
            name='writing_mode',
            field=models.CharField(choices=[('h-tb', 'horizontal-tb'), ('v-rl', 'vertical-rl'), ('v-lr', 'vertical-lr')], default='h-tb', max_length=10, verbose_name='writing mode'),
        ),
    ]
