# Generated by Django 4.2.13 on 2024-05-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0005_comicchaptertranslation_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicchaptertranslation',
            name='cover',
        ),
    ]
