# Generated by Django 4.2.13 on 2024-06-22 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0006_remove_post_language_post_writing_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trang_tranh.userprofile', verbose_name='user profile')),
            ],
        ),
    ]
