# Generated by Django 4.2.13 on 2024-06-22 15:06

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0009_pagetranslation_webp_image_alter_page_webp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='webp_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='webp-post-images/', verbose_name='webp image'),
        ),
    ]
