# Generated by Django 4.2.13 on 2024-06-23 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0010_postmedia_webp_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('adventure', 'Adventure'), ('sci-fi', 'Science Fiction'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('action', 'Action'), ('romance', 'Romance')], max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='comic',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='trang_tranh.genre', verbose_name='genre'),
        ),
    ]
