# Generated by Django 4.2.13 on 2024-06-28 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0012_userprofile_email_confirmed_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trang_tranh.chapter', verbose_name='about chapter'),
        ),
        migrations.AddField(
            model_name='post',
            name='about_comic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trang_tranh.comic', verbose_name='about comic'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='genre',
            field=models.ManyToManyField(to='trang_tranh.genre', verbose_name='genre'),
        ),
    ]
