# Generated by Django 4.2.13 on 2024-06-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0013_post_about_chapter_post_about_comic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio_writing_mode',
            field=models.CharField(blank=True, choices=[('h-tb', 'horizontal-tb'), ('v-rl', 'vertical-rl'), ('v-lr', 'vertical-lr')], max_length=50, null=True, verbose_name='bio writing mode'),
        ),
    ]
