# Generated by Django 4.2.13 on 2024-07-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0014_userprofile_bio_writing_mode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_genre_name'),
        ),
    ]
