# Generated by Django 4.2.13 on 2024-08-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0015_genre_unique_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('p', 'Public'), ('f', 'Followers'), ('ff', 'Following followers'), ('o', 'Only me')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.TextField(max_length=500, verbose_name='text content'),
        ),
    ]
