# Generated by Django 4.2.13 on 2024-09-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_tranh', '0017_post_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_comics', to='trang_tranh.userprofile', verbose_name='liked by'),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_posts', to='trang_tranh.userprofile', verbose_name='liked by'),
        ),
    ]
